import './globals.css'
import { Providers } from './components/providers/providers'
import { Roboto } from 'next/font/google'

const roboto = Roboto({
  weight: '300',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} md:text-xl`}>
          {children}
      </body>
    </html>
  )
}
